### ISSUE TITLE
Menu buttons act as toggles

### ISSUE THREAD

**Issue by panicbit** [RedFlames/CollabLobbyUI#1]
The menu buttons act as toggles, i.e. the "open menu" button can close the menu and the "close menu" button can open the menu.
I believe this part needs to be tweaked a little bit:

https://github.com/RedFlames/CollabLobbyUI/blob/e18f3e1be4676b03876859953e2a54d2ec5575c6/Entities/NavMenu.cs#L138-L140

**Comment by RedFlames** [comment]
Oh hey, I totally missed this, sorry about that. And yeah, I'm pretty sure the version you embedded there is already fixed, it was checking `Active` of the component (always being true) instead of my own `IsActive` there within the if conditional. I actually noticed this bug myself and fixed it here, but didn't release the fix to GameBanana. >w>

Should be fixed in v1.0.2 that I released today, right?

**Comment by panicbit** [comment]
Hey there! Seems like in 1.0.2 the "open menu" button can still toggle, but that behaviour I can work with (maybe that is even intended). The close button is acting properly as a close button, which fixes my actual issue. Thanks a lot! 😄 

(btw, love the teleport button you added ❤️)

**Comment by MechanicPig** [comment]
After pressing ESC to return from the pause menu, releasing it later will open the menu. I think the problem is caused by the code here. Is this intentional design?
